export const CATEGORIES_ACTIONS_TYPE = {
	SET_CATEGORIES: "category/SET_CATEGORIES",
	FETCH_CATEGORIES_START: "category/SET_CATEGORIES",
	FETCH_CATEGORIES_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
	FETCH_CATEGORIES_FAILED: "category/FETCH_CATEGORIES_FAILED",
};
