export const CART_ACTION_TYPE = {
	SET_IS_CART_OPEN: "cart/SET_IS_CART_OPEN",
	ADD_TO_CART: "cart/ADD_TO_CART",
	REMOVE_FROM_CART: "cart/REMOVE_FROM_CART",
	DELETE_ITEM: "cart/DELETE_ITEM",
	UPDATE_CART_ITEMS_COUNT: "cart/UPDATE_CART_ITEMS_COUNT",
};
